jobs:
  - job: checks
    displayName: static code analysis
    pool:
      vmImage: ubuntu-latest
    steps:
      # Use Python >=3.7 for syntax validation
      - task: UsePythonVersion@0
        displayName: Set up python
        inputs:
          versionSpec: 3.7

      # Run syntax validation on a shallow clone
      - bash: |
          python .azure-pipelines/syntax-validation.py
        displayName: Syntax validation

      # Run flake8 validation on a shallow clone
      - bash: |
          pip install flake8
          python .azure-pipelines/flake8-validation.py
        displayName: Flake8 validation

  - job: linux
    pool:
      vmImage: ubuntu-latest
    strategy:
      matrix:
        python35:
          PYTHON_VERSION: 3.5
        python36:
          PYTHON_VERSION: 3.6
        python37:
          PYTHON_VERSION: 3.7
        python38:
          PYTHON_VERSION: 3.8

    steps:
    - template: .azure-pipelines/ci.yml

  - job: macOS
    pool:
      vmImage: macOS-latest
    strategy:
      matrix:
        python35:
          PYTHON_VERSION: 3.5
        python36:
          PYTHON_VERSION: 3.6
        python37:
          PYTHON_VERSION: 3.7
        python38:
          PYTHON_VERSION: 3.8

    steps:
    - template: .azure-pipelines/ci.yml

  - job: windows
    pool:
      vmImage: windows-latest
    strategy:
      matrix:
        python35:
          PYTHON_VERSION: 3.5
        python36:
          PYTHON_VERSION: 3.6
        python37:
          PYTHON_VERSION: 3.7
        python38:
          PYTHON_VERSION: 3.8

    steps:
    - template: .azure-pipelines/ci.yml
