# Config file for automatic testing at travis-ci.org

language: python

matrix:
  include:
    - python: 3.8
    - python: 3.7
    - python: 3.6
    - os: osx
      language: generic
      env: CONDA=3.8 TOXENV=py38
    - os: osx
      language: generic
      env: CONDA=3.7 TOXENV=py37
    - os: osx
      language: generic
      env: CONDA=3.6 TOXENV=py36

  allow_failures:
    - env: OPTIONAL=1

  fast_finish: true

before_install: |
  if [ ! -z "$CONDA" ]; then
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh --output miniconda.sh
    fi
    chmod +x miniconda.sh
    ./miniconda.sh -b
    export PATH=$HOME/miniconda3/bin:$PATH
    conda update --yes conda
    conda create --yes -n travis python=$CONDA
    source activate travis
    # A manual check that the correct version of Python is running.
    python --version
  fi

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox
