environment:

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
      UNSTABLE: 1
    - PYTHON: "C:\\Python35"
      UNSTABLE: 1
    - PYTHON: "C:\\Python36"
      UNSTABLE: 1
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34-x64"
      UNSTABLE: 1
    - PYTHON: "C:\\Python35-x64"
      UNSTABLE: 1
    - PYTHON: "C:\\Python36-x64"
      UNSTABLE: 1

matrix:
  allow_failures:
    - UNSTABLE: 1

install:
  # Upgrade to the latest pip.
  - '%PYTHON%\\python.exe -m pip install -U pip setuptools wheel'

build: off

test_script:
  # Note that you must use the environment variable %PYTHON% to refer to
  # the interpreter you're using - Appveyor does not do anything special
  # to put the Python version you want to use on PATH.
  - "%PYTHON%\\python.exe setup.py test"

after_test:
  # This step builds your wheels.
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.
